version: 43
jobs:
- name: pusher all-branch commit
  steps:
  - type: PushRepository
    name: (not force) to gh yhm-amber/lang-note
    remoteUrl: https://github.com/yhm-amber/lang-note.git
    userName: yhm-amber
    passwordSecret: github.yhm-amber
    force: false
    condition: ALWAYS
    optional: false
  - type: PushRepository
    name: (force) to cb yhm-ypa/lang-note
    remoteUrl: https://codeberg.org/yhm-ypa/lang-note.git
    userName: yhm
    passwordSecret: codeberg.yhm
    force: true
    condition: ALWAYS
    optional: false
  - type: PushRepository
    name: (force) to disrootfj ypayhm/lang-note
    remoteUrl: https://git.disroot.org/ypayhm/lang-note.git
    userName: ypayhm
    passwordSecret: disroot.ypayhm
    force: true
    condition: ALWAYS
    optional: false
  triggers:
  - type: BranchUpdateTrigger
    userMatch: anyone
    projects: yhm-ypa/lang-note
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
- name: puller all-branch cron.03:20:10
  steps:
  - type: PullRepository
    name: (not force) from gh yhm-amber/lang-note
    remoteUrl: https://github.com/yhm-amber/lang-note.git
    refs: refs/heads/* refs/tags/*
    withLfs: true
    force: false
    condition: ALWAYS
    optional: false
  - type: PullRepository
    name: (not force) from cb yhm-ypa/lang-note
    remoteUrl: https://codeberg.org/yhm-ypa/lang-note.git
    refs: refs/heads/* refs/tags/*
    withLfs: true
    force: false
    condition: ALWAYS
    optional: false
  - type: PullRepository
    name: (not force) from disrootfj ypayhm/lang-note
    remoteUrl: https://git.disroot.org/ypayhm/lang-note.git
    refs: refs/heads/* refs/tags/*
    withLfs: true
    force: false
    condition: ALWAYS
    optional: false
  triggers:
  - type: ScheduleTrigger
    cronExpression: 10 20 3 * * ?
    projects: yhm-ypa/lang-note
  retryCondition: never
  maxRetries: 3
  retryDelay: 30
  timeout: 3600
